default_context:
  project_name: 'Yandex Hack - 3+2'
  project_slug: 'yandex-hack---3+2'
  domain_main: 'yandex-hack-32.xyz'
  domain_staging: 'stag.yandex-hack-32.xyz'
  docker_swarm_stack_name_main: 'yandex-hack-32-xyz'
  docker_swarm_stack_name_staging: 'stag-yandex-hack-32-xyz'
  secret_key: 'c802c18e451d2fc0d6dec97c222de20e5c222aedcd012296c5bf16f9f0375a71'
  first_superuser: 'admin'
  first_superuser_password: 'KkNgG4uyNXd67t5e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.yandex-hack-32.xyz", "https://stag.yandex-hack-32.xyz", "https://yandex-hack-32.xyz", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@yandex-hack-32.xyz'
  postgres_password: '5UARK7Rqrn6cwPJV'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: '5UARK7Rqrn6cwPJV'
  traefik_constraint_tag: 'yandex-hack-32.xyz'
  traefik_constraint_tag_staging: 'stag.yandex-hack-32.xyz'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:KkNgG4uyNXd67t5e'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
